method: grid
metric:
  goal: maximize
  name: final_avg_accuracy
parameters:
  alpha_I:
    distribution: categorical
    values:
      - 0.0001
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
  batch_size:
    value: 256
  beta_efc:
    distribution: categorical
    values:
      - 0.01
      - 0.05
      - 0.1
      - 0.2
      - 0.5
      - 1
      - 2
      - 5
      - 10
  lr:
    distribution: categorical
    values:
      - 1e-06
      - 1e-05
      - 1e-04
      - 1e-03
      - 1e-02
  method:
    value: efc
  optimizer:
    value: Adam
  seed:
    distribution: categorical
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
  target_lr:
    distribution: categorical
    values:
      - 1e-02
      - 5e-02
      - 1e-01
program: train.py
