method: grid
metric:
  goal: maximize
  name: final_avg_accuracy
parameters:
  alpha_I:
    distribution: categorical
    values:
      - 0.0001
      - 0.001
      - 0.01
  batch_size:
    value: 256
  beta_efc:
    distribution: categorical
    values:
      - 0.01
      - 0.1
      - 1
      - 10
  lr:
    distribution: categorical
    values:
      - 1e-06
      - 5e-06
      - 1e-05
      - 5e-05
      - 1e-04
  method:
    value: efc
  optimizer:
    value: Adam
  seed:
    distribution: categorical
    values:
      - 1
      - 2
      - 3
  target_lr:
    distribution: categorical
    values:
      - 1e-02
      - 1e-01
  setting:
    value: classIL
program: train.py
