method: grid
metric:
  goal: maximize
  name: final_avg_accuracy
parameters:
  num_workers:
    value: 0
  alpha_di:
    distribution: categorical
    values:
      - 0.0001
      - 0.001
  batch_size:
    value: 256
  beta_efc:
    distribution: categorical
    values:
      - 0.1
      - 0.5
      - 1
      - 5
      - 20
  eps:
    distribution: categorical
    values:
      - 1e-03
      - 1e-04
      - 2e-04
      - 2e-05
  lr:
    distribution: categorical
    values:
      - 5e-06
      - 1e-05
      - 5e-05
      - 1e-04
  method:
    values:
      - efc
      - bp 
      - ewc
  optimizer:
    distribution: categorical
    values:
      - Adam
      - SGD
  seed:
    distribution: categorical
    values:
      - 1
      - 2
      - 3
  tau:
    distribution: categorical
    values:
      - 1e-5
      - 1e-4
      - 1e-3
      - 1e-2
      - 1e-1
  target_lr:
    distribution: categorical
    values:
      - 1e-03
      - 5e-03
      - 1e-02
program: trainer_classIL.py
