method: grid
metric:
  goal: maximize
  name: final_avg_accuracy
parameters:
  num_workers:
    value: 0
  batch_size:
    value: 256
  beta_efc:
    distribution: categorical
    values:
      - 0.1
      - 0.5
      - 1
      - 5
      - 10
      - 50
      - 100
      - 500
      - 1000
      - 5000
  psi_lr:
    distribution: categorical
    values:
      - 0.5
      - 0.1
      - 0.05
      - 0.01
  target_lr:
    distribution: categorical
    values:
      - 1
  lr:
    distribution: categorical
    values:
      - 1e-03
  method:
    value: efc_bp
  optimizer:
    distribution: categorical
    values:
      - Adam
  seed:
    distribution: categorical
    values:
      - 69
      - 42
      - 6969
      - 4242
      - 6942
  eps:
    distribution: categorical
    values:
      - 1e-01
      - 1e-02
      - 1e-03
program: trainer_classIL.py
